# Generated by Django 5.0.7 on 2024-10-01 01:51

import django.core.validators
import django.db.models.deletion
import inventario.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agenda', '0001_initial'),
        ('configuracion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('rentabilidad', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ],
            options={
                'verbose_name': 'categoria',
                'verbose_name_plural': '📚 Categorias',
            },
        ),
        migrations.CreateModel(
            name='Presentacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('unidad_de_medida', models.CharField(choices=[('Unidades', 'Unidades'), ('Kilos', 'Kilos'), ('Gramos', 'Gramos'), ('Litros', 'Litros'), ('Mililitros', 'Mililitros'), ('Mt2s', 'Mt2s'), ('Mts', 'Mts'), ('Cms', 'Cms'), ('Onzas', 'Onzas'), ('Libras', 'Libras')], default='Unidades', max_length=50)),
            ],
            options={
                'verbose_name': 'presentacion',
                'verbose_name_plural': '🍶 Presentacion',
            },
        ),
        migrations.CreateModel(
            name='deposito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('telefono', models.CharField(blank=True, max_length=255, null=True)),
                ('contactos', models.CharField(blank=True, max_length=255, null=True, verbose_name='Campo libre')),
                ('cuit', models.CharField(blank=True, max_length=255, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuracion.configuracion')),
            ],
            options={
                'verbose_name': 'deposito',
                'verbose_name_plural': '🏭 Depositos',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=100, null=True)),
                ('nombre', models.CharField(default='SIN NOMBRE ASIGNADO', max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='img/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif']), inventario.models.validate_image_size])),
                ('cantidad', models.DecimalField(decimal_places=2, default=1, max_digits=20)),
                ('unidad_de_medida', models.CharField(choices=[('Unidades', 'Unidades'), ('Kilos', 'Kilos'), ('Gramos', 'Gramos'), ('Litros', 'Litros'), ('Mililitros', 'Mililitros'), ('Mt2s', 'Mt2s'), ('Mts', 'Mts'), ('Cms', 'Cms'), ('Onzas', 'Onzas'), ('Libras', 'Libras')], default='Unidades', max_length=50)),
                ('habilitar_venta', models.BooleanField(default=True)),
                ('ultima_modificacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.categoria')),
                ('deposito', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.deposito')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agenda.proveedor')),
            ],
            options={
                'verbose_name': 'producto',
                'verbose_name_plural': '📦 Productos',
            },
        ),
        migrations.CreateModel(
            name='MovimientoProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('entrada', models.DecimalField(decimal_places=2, default=0, max_digits=25)),
                ('salida', models.DecimalField(decimal_places=2, default=0, max_digits=25)),
                ('inventario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.deposito')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.producto')),
            ],
            options={
                'verbose_name': 'movimiento',
                'verbose_name_plural': '🔀 Movimientos',
            },
        ),
        migrations.CreateModel(
            name='Merma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now=True)),
                ('cantidad', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('costos_totales', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('motivo', models.CharField(max_length=255)),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.producto')),
            ],
            options={
                'verbose_name': 'merma',
                'verbose_name_plural': '⛔ Mermas',
            },
        ),
        migrations.CreateModel(
            name='ProductoPrecio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1)),
                ('rentabilidad', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('precio_manual', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('unidad_de_medida', models.CharField(choices=[('Unidades', 'Unidades'), ('Kilos', 'Kilos'), ('Gramos', 'Gramos'), ('Litros', 'Litros'), ('Mililitros', 'Mililitros'), ('Mt2s', 'Mt2s'), ('Mts', 'Mts'), ('Cms', 'Cms'), ('Onzas', 'Onzas'), ('Libras', 'Libras')], default='Unidades', max_length=50)),
                ('lista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='configuracion.listadeprecio')),
                ('presentacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.presentacion')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.producto')),
            ],
            options={
                'verbose_name': 'precio',
                'verbose_name_plural': '💱 Precios de productos',
            },
        ),
    ]
