# Generated by Django 5.0 on 2024-10-11 02:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0013_alter_chofer_usuario'),
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deposito',
            name='contactos',
        ),
        migrations.RemoveField(
            model_name='deposito',
            name='cuit',
        ),
        migrations.RemoveField(
            model_name='deposito',
            name='empresa',
        ),
        migrations.AlterField(
            model_name='categoria',
            name='rentabilidad',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Esta rentabilidad es la usada para los casos en los que el aumento de los productos sea por "categoria"', max_digits=5),
        ),
        migrations.AlterField(
            model_name='producto',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agenda.proveedor', verbose_name='Proveedor Ult. Compra'),
        ),
    ]
