# Generated by Django 5.0 on 2024-10-11 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_remove_producto_deposito_alter_producto_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presentacion',
            name='unidad_de_medida',
        ),
    ]
