# Generated by Django 5.0 on 2024-10-11 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_remove_presentacion_unidad_de_medida'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='costo_unitario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Ultimo costo Unitario'),
        ),
    ]
