# Generated by Django 5.0 on 2024-10-11 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_alter_productoprecio_precio_manual'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoprecio',
            name='precio_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='productoprecio',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
