# Generated by Django 5.0 on 2024-10-11 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_productoprecio_precio_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='costo_unitario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
