# Generated by Django 5.0 on 2024-10-14 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0009_deposito_pin_maps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='habilitar_venta',
            field=models.BooleanField(default=False),
        ),
    ]
