# Generated by Django 5.0.7 on 2024-10-19 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0010_alter_producto_habilitar_venta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='rentabilidad',
        ),
    ]
