# Generated by Django 5.0.7 on 2024-10-19 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0011_remove_categoria_rentabilidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientoproducto',
            name='detalle',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='movimientoproducto',
            name='estado',
            field=models.BooleanField(default=False),
        ),
    ]
