# Generated by Django 5.0.7 on 2024-10-28 23:20

import django.core.validators
import django.db.models.deletion
import inventario.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0014_movimientoproducto_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='tipo',
            field=models.CharField(choices=[('Simple', 'Simple'), ('Compuesto', 'Compuesto')], default='Simple', max_length=10),
        ),
        migrations.CreateModel(
            name='RecetaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unidad_de_medida', models.CharField(choices=[('Unidades', 'Unidades'), ('Kilos', 'Kilos'), ('Gramos', 'Gramos'), ('Litros', 'Litros'), ('Mililitros', 'Mililitros'), ('Mt2s', 'Mt2s'), ('Mts', 'Mts'), ('Cms', 'Cms'), ('Onzas', 'Onzas'), ('Libras', 'Libras')], max_length=50)),
                ('producto_principal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recetas', to='inventario.producto')),
                ('producto_usado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usado_en_recetas', to='inventario.producto')),
            ],
        ),
    ]
