# Generated by Django 5.0.7 on 2024-10-29 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0017_alter_producto_imagen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recetaproducto',
            options={'verbose_name': 'composicion', 'verbose_name_plural': '🛠️ Composicion'},
        ),
    ]
