# Generated by Django 5.0 on 2024-10-01 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agenda', '0003_alter_onboardingproveedor_nombre_empresa'),
    ]

    operations = [
        migrations.CreateModel(
            name='solicitudEmprendimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_alta', models.DateTimeField(auto_now_add=True, null=True)),
                ('fecha_habilitacion', models.DateTimeField(blank=True, null=True)),
                ('habilitado', models.BooleanField(default=False)),
                ('emprendimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.onboardingproveedor')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.proveedor')),
            ],
            options={
                'verbose_name': 'proveedor',
                'verbose_name_plural': '🧑\u200d🔧 Proveedores',
            },
        ),
    ]
