# Generated by Django 5.0 on 2024-10-01 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solicitudemprendimiento',
            options={'verbose_name': 'solicitud', 'verbose_name_plural': '🎡 Sol. Emprendimiento'},
        ),
    ]
