# Generated by Django 5.0 on 2024-10-01 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0002_alter_solicitudemprendimiento_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solicitudemprendimiento',
            options={'verbose_name': 'solicitud', 'verbose_name_plural': '🎡 Solicitudes'},
        ),
    ]
