# Generated by Django 5.0.7 on 2024-10-20 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Landing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_hero', models.BooleanField(default=False)),
                ('hero_title', models.CharField(max_length=200, null=True)),
                ('hero_description', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
