# Generated by Django 5.0.7 on 2024-10-20 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='landing',
            name='category_1',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='landing',
            name='category_2',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='landing',
            name='category_3',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='landing',
            name='category_4',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='landing',
            name='section_category',
            field=models.BooleanField(default=False),
        ),
    ]
