# Generated by Django 5.0.7 on 2024-10-20 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0002_landing_category_1_landing_category_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='landing',
            name='section_gallery',
            field=models.BooleanField(default=False),
        ),
    ]
