# Generated by Django 5.0.7 on 2024-10-20 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0005_landing_comment_1_landing_comment_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='landing',
            name='about_us_text_1',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='landing',
            name='about_us_text_2',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='landing',
            name='about_us_text_3',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='landing',
            name='about_us_title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
