# Generated by Django 5.0.7 on 2024-10-20 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0006_landing_about_us_text_1_landing_about_us_text_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='landing',
            name='hero_background_image',
            field=models.ImageField(blank=True, null=True, upload_to='img/landing/'),
        ),
    ]
