# Generated by Django 5.0.7 on 2024-10-20 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0008_landing_category_1_image_landing_category_2_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='landing',
            name='gallery_1_image',
            field=models.ImageField(blank=True, null=True, upload_to='img/landing/'),
        ),
        migrations.AddField(
            model_name='landing',
            name='gallery_2_image',
            field=models.ImageField(blank=True, null=True, upload_to='img/landing/'),
        ),
        migrations.AddField(
            model_name='landing',
            name='gallery_3_image',
            field=models.ImageField(blank=True, null=True, upload_to='img/landing/'),
        ),
        migrations.AddField(
            model_name='landing',
            name='gallery_4_image',
            field=models.ImageField(blank=True, null=True, upload_to='img/landing/'),
        ),
        migrations.AddField(
            model_name='landing',
            name='gallery_5_image',
            field=models.ImageField(blank=True, null=True, upload_to='img/landing/'),
        ),
        migrations.AddField(
            model_name='landing',
            name='gallery_6_image',
            field=models.ImageField(blank=True, null=True, upload_to='img/landing/'),
        ),
    ]
