# Generated by Django 5.0.7 on 2024-10-21 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0010_landing_gallery_descripcion_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='landing',
            name='features_icon_1',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='landing',
            name='features_icon_2',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='landing',
            name='features_icon_3',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='landing',
            name='features_subtitle_1',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='landing',
            name='features_subtitle_2',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='landing',
            name='features_subtitle_3',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='landing',
            name='features_text_1',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='landing',
            name='features_text_2',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='landing',
            name='features_text_3',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='landing',
            name='features_title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
