# Generated by Django 5.0.7 on 2024-10-21 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0011_landing_features_icon_1_landing_features_icon_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='landing',
            name='cta_btn_label',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='landing',
            name='cta_btn_url',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='landing',
            name='cta_text',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='landing',
            name='cta_title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='landing',
            name='newsletter_btn_label',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='landing',
            name='newsletter_text',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='landing',
            name='newsletter_title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
