# Generated by Django 5.0.7 on 2024-10-21 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0012_landing_cta_btn_label_landing_cta_btn_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='landing',
            name='about_us_image',
            field=models.ImageField(blank=True, null=True, upload_to='img/landing/'),
        ),
    ]
