# Generated by Django 5.0.7 on 2024-10-21 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0013_landing_about_us_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='landing',
            name='nombre',
            field=models.CharField(default='pagina_inicio', max_length=255, unique=True),
        ),
    ]
