# Generated by Django 5.0.7 on 2024-10-22 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0015_section_landing_sections'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='landing',
            options={'verbose_name': 'pagina', 'verbose_name_plural': '🖥️ Website'},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'verbose_name': 'orden', 'verbose_name_plural': '🕌 Orden de Secciones'},
        ),
        migrations.AlterField(
            model_name='section',
            name='landing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_set', to='front.landing'),
        ),
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(choices=[('section_hero', 'Hero Section'), ('section_category', 'Category Section'), ('section_gallery', 'Gallery Section'), ('about_us', 'About Us Section'), ('testimonials', 'Testimonials Section'), ('features', 'Features Section'), ('cta_section', 'Call to Action Section'), ('newsletter', 'Newsletter Section')], max_length=255),
        ),
    ]
