# Generated by Django 5.0.7 on 2024-11-01 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0019_landing_banner_1_image_landing_banner_1_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='landing',
            name='section_how_we_work',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='landing',
            name='step_description_1',
            field=models.TextField(blank=True, default='Llámanos o envíanos un mensaje con tu pedido.', null=True),
        ),
        migrations.AddField(
            model_name='landing',
            name='step_description_2',
            field=models.TextField(blank=True, default='Seleccionamos las verduras frescas que solicitaste.', null=True),
        ),
        migrations.AddField(
            model_name='landing',
            name='step_description_3',
            field=models.TextField(blank=True, default='Te enviamos la confirmación de tu pedido.', null=True),
        ),
        migrations.AddField(
            model_name='landing',
            name='step_description_4',
            field=models.TextField(blank=True, default='Realizamos la entrega a domicilio martes y jueves.', null=True),
        ),
        migrations.AddField(
            model_name='landing',
            name='step_emoji_1',
            field=models.CharField(blank=True, default='📞', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='landing',
            name='step_emoji_2',
            field=models.CharField(blank=True, default='🥕', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='landing',
            name='step_emoji_3',
            field=models.CharField(blank=True, default='✅', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='landing',
            name='step_emoji_4',
            field=models.CharField(blank=True, default='🚚', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='landing',
            name='step_title_1',
            field=models.CharField(blank=True, default='Realiza tu Pedido', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='landing',
            name='step_title_2',
            field=models.CharField(blank=True, default='Preparamos tu Pedido', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='landing',
            name='step_title_3',
            field=models.CharField(blank=True, default='Confirmación', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='landing',
            name='step_title_4',
            field=models.CharField(blank=True, default='Entrega', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='landing',
            name='work_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(choices=[('section_hero', 'Hero Section'), ('section_category', 'Category Section'), ('banner', 'Banner'), ('section_gallery', 'Gallery Section'), ('about_us', 'About Us Section'), ('testimonials', 'Testimonials Section'), ('features', 'Features Section'), ('cta_section', 'Call to Action Section'), ('como_trabajamos', 'Como Trabajamos'), ('newsletter', 'Newsletter Section'), ('section_clients', 'Nuestros Clientes Section'), ('footer', 'Footer Section')], max_length=255),
        ),
    ]
