# Generated by Django 5.0.7 on 2024-11-01 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0020_landing_section_how_we_work_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='landing',
            name='background_color_hww',
            field=models.CharField(default='#ffffff', help_text='Color de fondo en formato hexadecimal (ej. #ffffff para blanco)', max_length=7),
        ),
    ]
