# Generated by Django 5.0.7 on 2024-10-01 01:51

import agenda.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=200, null=True, unique=True, verbose_name='documento')),
                ('nombre', models.CharField(max_length=200, null=True)),
                ('apellido', models.CharField(max_length=200, null=True)),
                ('telefono', models.CharField(blank=True, default=1, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('habilitado', models.BooleanField(default=False)),
                ('habilitar_cc', models.BooleanField(default=False)),
                ('tiene_cuenta', models.BooleanField(default=False)),
                ('cuit', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'cliente',
                'verbose_name_plural': '🧑\u200d💼 Clientes',
            },
        ),
        migrations.CreateModel(
            name='DireccionEntregaCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=150)),
                ('localidad', models.CharField(max_length=150, null=True)),
                ('barrio', models.CharField(blank=True, max_length=150, null=True)),
                ('entre_calle_1', models.CharField(blank=True, max_length=150)),
                ('entre_calle_2', models.CharField(blank=True, max_length=150)),
                ('hora_desde', models.TimeField(default='09:00:00')),
                ('hora_hasta', models.TimeField(default='18:00:00')),
                ('comentarios', models.CharField(blank=True, max_length=150)),
            ],
            options={
                'verbose_name': 'direccion',
                'verbose_name_plural': '🏠 Dirección de Entrega',
            },
        ),
        migrations.CreateModel(
            name='OnboardingProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(max_length=255, verbose_name='Nombre de la Empresa')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='img/logos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif']), agenda.models.validate_image_size])),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('cuit', models.CharField(max_length=11, unique=True, verbose_name='CUIT')),
                ('direccion', models.CharField(max_length=255, verbose_name='Dirección')),
                ('telefono_contacto', models.CharField(max_length=20, verbose_name='Teléfono de Contacto')),
                ('redes_sociales', models.JSONField(blank=True, null=True, verbose_name='Redes Sociales')),
                ('horario_atencion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Horarios de Atención')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Solicitud')),
                ('aprobado', models.BooleanField(default=False, verbose_name='Aprobado')),
            ],
            options={
                'verbose_name': 'onboarding',
                'verbose_name_plural': '👩🏻\u200d💼👨🏻\u200d💼 Onboarding Emprendimiento',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_alta', models.DateTimeField(auto_now_add=True, null=True)),
                ('fecha_habilitacion', models.DateTimeField(blank=True, null=True)),
                ('habilitado', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'proveedor',
                'verbose_name_plural': '🧑\u200d🔧 Proveedores',
            },
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('apellido', models.CharField(max_length=120)),
            ],
            options={
                'verbose_name': 'vendedor',
                'verbose_name_plural': '🪪 Vendedores',
            },
        ),
        migrations.CreateModel(
            name='Chofer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'chofer',
                'verbose_name_plural': '🧑🏻\u200d🔧 Chofer',
            },
        ),
    ]
