# Generated by Django 5.0 on 2024-10-01 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onboardingproveedor',
            name='nombre_empresa',
            field=models.CharField(max_length=255, verbose_name='Nombre del emprendimiento'),
        ),
    ]
