# Generated by Django 5.0 on 2024-10-01 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0003_alter_onboardingproveedor_nombre_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onboardingproveedor',
            name='horario_atencion',
            field=models.CharField(max_length=255, null=True, verbose_name='Horarios de Atención'),
        ),
    ]
