# Generated by Django 5.0 on 2024-10-01 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0004_alter_onboardingproveedor_horario_atencion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onboardingproveedor',
            name='redes_sociales',
        ),
        migrations.AddField(
            model_name='onboardingproveedor',
            name='correo',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='onboardingproveedor',
            name='facebook',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Facebook'),
        ),
        migrations.AddField(
            model_name='onboardingproveedor',
            name='instagram',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='onboardingproveedor',
            name='tiktok',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Tiktok'),
        ),
        migrations.AddField(
            model_name='onboardingproveedor',
            name='twitter',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Twitter '),
        ),
    ]
