# Generated by Django 5.0 on 2024-10-10 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0005_remove_onboardingproveedor_redes_sociales_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='onboardingproveedor',
            options={'verbose_name': 'empresa', 'verbose_name_plural': '🏭 Empresa'},
        ),
        migrations.RemoveField(
            model_name='onboardingproveedor',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='onboardingproveedor',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='onboardingproveedor',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='onboardingproveedor',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='onboardingproveedor',
            name='tiktok',
        ),
        migrations.RemoveField(
            model_name='onboardingproveedor',
            name='twitter',
        ),
        migrations.AlterField(
            model_name='onboardingproveedor',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='onboardingproveedor',
            name='horario_atencion',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Horarios de Atención'),
        ),
        migrations.AlterField(
            model_name='onboardingproveedor',
            name='nombre_empresa',
            field=models.CharField(max_length=255, verbose_name='Nombre de la empresa'),
        ),
        migrations.AlterField(
            model_name='onboardingproveedor',
            name='telefono_contacto',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono de Contacto'),
        ),
    ]
