# Generated by Django 5.0 on 2024-10-10 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0006_alter_onboardingproveedor_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboardingproveedor',
            name='prueba',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
