# Generated by Django 5.0 on 2024-10-10 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0007_onboardingproveedor_prueba'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onboardingproveedor',
            name='prueba',
        ),
    ]
