# Generated by Django 5.0 on 2024-10-10 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0008_remove_onboardingproveedor_prueba'),
        ('configuracion', '0003_remove_configuracion_proveedor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='nombre',
            new_name='nombre_apellido',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='email',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='tiene_cuenta',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='lista_de_precio',
            field=models.ForeignKey(blank=True, help_text='Si no se asigna lista, el usuario no podrá ver ningun producto para solicitar.', null=True, on_delete=django.db.models.deletion.CASCADE, to='configuracion.listadeprecio', verbose_name='Lista de Precio Asignada'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='vendedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agenda.vendedor', verbose_name='Vendedor asignado'),
        ),
    ]
