# Generated by Django 5.0 on 2024-10-10 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0009_rename_nombre_cliente_nombre_apellido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='fecha_alta',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='fecha_habilitacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
