# Generated by Django 5.0 on 2024-10-11 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0010_cliente_fecha_alta_cliente_fecha_habilitacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendedor',
            name='habilitado',
            field=models.BooleanField(default=False),
        ),
    ]
