# Generated by Django 5.0 on 2024-10-11 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0011_vendedor_habilitado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chofer',
            name='nombre',
        ),
        migrations.AddField(
            model_name='chofer',
            name='fecha_habilitacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chofer',
            name='habilitado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendedor',
            name='fecha_habilitacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
