# Generated by Django 5.0 on 2024-10-12 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0013_alter_chofer_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patente', models.CharField(max_length=200, null=True, unique=True)),
                ('vehiculo', models.CharField(max_length=200, null=True)),
                ('habilitado', models.BooleanField(default=False)),
                ('fecha_habilitacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'vehiculo',
                'verbose_name_plural': '🛻 Flota Vehiculos',
            },
        ),
    ]
