# Generated by Django 5.0 on 2024-10-12 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0014_flota'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboardingproveedor',
            name='pin_maps',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='onboardingproveedor',
            name='nombre_empresa',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='onboardingproveedor',
            name='telefono_contacto',
            field=models.CharField(max_length=20, null=True, verbose_name='Teléfono de Contacto'),
        ),
    ]
