# Generated by Django 5.0 on 2024-10-12 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0016_alter_onboardingproveedor_direccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='direccionentregacliente',
            name='pin_maps',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
