# Generated by Django 5.0 on 2024-10-13 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0009_deposito_pin_maps'),
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempedido',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=25),
        ),
        migrations.AddField(
            model_name='itempedido',
            name='producto_precio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.productoprecio'),
        ),
        migrations.AlterField(
            model_name='itempedido',
            name='producto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.producto'),
        ),
    ]
