# Generated by Django 5.0.7 on 2024-10-17 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0017_direccionentregacliente_pin_maps'),
        ('pedidos', '0003_alter_pedido_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='DireccionEntregaCliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='agenda.direccionentregacliente'),
        ),
    ]
