# Generated by Django 5.0.7 on 2024-10-17 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0004_pedido_direccionentregacliente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='DireccionEntregaCliente',
            new_name='direccion_entrega_cliente',
        ),
    ]
