# Generated by Django 5.0.7 on 2024-10-22 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0006_alter_pedido_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('abierto', 'Abierto'), ('pendiente', 'Pendiente'), ('en_preparacion', 'En preparacion'), ('listo', 'Listo'), ('en_camino', 'En camino'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='abierto', max_length=20),
        ),
    ]
