# Generated by Django 5.0.7 on 2024-10-29 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0019_alter_categoria_imagen'),
        ('pedidos', '0007_alter_pedido_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='deposito',
            field=models.ForeignKey(blank=True, default=1, help_text='Deposito donde saldrá la mercadería.', null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.deposito', verbose_name='Deposito salida'),
        ),
    ]
