# Generated by Django 5.0.7 on 2024-10-01 01:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configuracion', '0001_initial'),
        ('contabilidad', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediodecompra',
            name='cuenta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contabilidad.cuentas'),
        ),
        migrations.AddField(
            model_name='mediodeventa',
            name='cuenta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contabilidad.cuentas'),
        ),
        migrations.AddField(
            model_name='mediodeventa',
            name='moneda',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='configuracion.monedas'),
        ),
        migrations.AddField(
            model_name='mediodecompra',
            name='moneda',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='configuracion.monedas'),
        ),
        migrations.AddField(
            model_name='configuracion',
            name='Moneda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moneda_principal', to='configuracion.monedas'),
        ),
        migrations.AddField(
            model_name='configuracion',
            name='Moneda_secundaria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moneda_secundaria', to='configuracion.monedas'),
        ),
    ]
