# Generated by Django 5.0 on 2024-10-10 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracion',
            name='proveedor',
        ),
    ]
