# Generated by Django 5.0 on 2024-10-10 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0003_remove_configuracion_proveedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracion',
            name='mail_bienvenida_cliente',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='configuracion',
            name='mail_bienvenida_proveedor',
            field=models.BooleanField(default=False),
        ),
    ]
