# Generated by Django 5.0 on 2024-10-11 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0004_configuracion_mail_bienvenida_cliente_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'inventario',
                'verbose_name_plural': '🏢 Inventarios',
            },
        ),
    ]
