# Generated by Django 5.0 on 2024-10-11 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0005_inventario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Inventario',
        ),
    ]
