# Generated by Django 5.0 on 2024-10-11 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0006_delete_inventario'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracion',
            name='unidad_de_medida_precio_venta',
            field=models.BooleanField(default=False, verbose_name='Permite Modificar la unidad de medida del precio del producto'),
        ),
    ]
