# Generated by Django 5.0 on 2024-10-11 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0007_configuracion_unidad_de_medida_precio_venta'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracion',
            name='valuar_stock_negativo',
            field=models.BooleanField(default=False, help_text='Si desea que el stock negativo reste de su valuacion, deje esta casilla en Verdadero.'),
        ),
    ]
