# Generated by Django 5.0 on 2024-10-11 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0008_configuracion_valuar_stock_negativo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracion',
            name='precio_venta_automatico',
            field=models.BooleanField(default=False, help_text='Si desea que el precio de venta del producto se calcule en base a una rentabilidad sobre el costo, deje esta casilla en Verdadero. En el caso contrario, se habilitará una casilla para colocar el precio final de venta.', verbose_name='Precio venta basado en rentabilidad'),
        ),
        migrations.AlterField(
            model_name='configuracion',
            name='unidad_de_medida_precio_venta',
            field=models.BooleanField(default=False, help_text='Permite Modificar la unidad de medida del precio del producto'),
        ),
    ]
