# Generated by Django 5.0 on 2024-10-11 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0009_alter_configuracion_precio_venta_automatico_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracion',
            name='venta_stock_negativo',
            field=models.BooleanField(default=False, help_text='Si desea vender sin limites de inventario, deje esta casilla en Verdadero. (Genera Stock Negativo)'),
        ),
    ]
