# Generated by Django 5.0 on 2024-10-11 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0010_alter_configuracion_venta_stock_negativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracion',
            name='confirmar_descarga_compra',
            field=models.BooleanField(default=True, help_text='Esta opcion permite al usuario confirmar cuando la mercaderia se ingresó correctamente a inventario. [📦 Iniciar descarga]'),
        ),
        migrations.AddField(
            model_name='configuracion',
            name='confirmar_viaje_compra',
            field=models.BooleanField(default=True, help_text='Esta opcion permite al usuario confirmar cuando la compra llega al deposito de ingreso. [🚚 llegada]'),
        ),
    ]
