# Generated by Django 5.0 on 2024-10-11 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0011_configuracion_confirmar_descarga_compra_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracion',
            name='confirmar_pisar_costo',
            field=models.BooleanField(default=True, help_text='Si desea actualizar el costo unitario de forma automática según la ultima compra, deje esta casilla en Verdadero. (En falso, se muestra casilla ✔️ Actualizar Costo en producto comprado)'),
        ),
    ]
