# Generated by Django 5.0 on 2024-10-12 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0012_configuracion_confirmar_pisar_costo'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracion',
            name='gastos_fletes_compras',
            field=models.CharField(choices=[('Distribuir costo en productos', 'Distribuir costo en productos'), ('Tratar el flete como GASTOS VARIOS', 'Tratar el flete como GASTOS VARIOS')], default='Distribuir costo en productos', max_length=50),
        ),
    ]
