# Generated by Django 5.0 on 2024-10-12 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0013_configuracion_gastos_fletes_compras'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracion',
            name='gastos_fletes_compras',
            field=models.CharField(choices=[('Distribuir costo en productos', 'Distribuir costo en productos'), ('Tratar el flete como GASTOS VARIOS', 'Tratar el flete como GASTOS VARIOS')], default='Distribuir costo en productos', help_text='Si usted desea que el gasto del flete al hacer la compra se distribuya entre los productos comprados (Actualiza costo tomando el flete), Debe seleccionar "Distribuir costo en productos", en caso contrario el gasto del flete irá a la cuenta de GASTOS VARIOS.', max_length=50),
        ),
    ]
