# Generated by Django 5.0 on 2024-10-12 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0014_alter_configuracion_gastos_fletes_compras'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracion',
            name='editar_fecha_compra',
            field=models.BooleanField(default=False, help_text='Si desea poder editar la fecha en la compra, deje esta casilla en Verdadero.'),
        ),
    ]
