# Generated by Django 5.0 on 2024-10-14 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0015_configuracion_editar_fecha_compra'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracion',
            name='limite_pedidos_pendientes',
            field=models.PositiveIntegerField(default=2),
        ),
    ]
