# Generated by Django 5.0.7 on 2024-10-19 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0016_configuracion_limite_pedidos_pendientes'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracion',
            name='gestionar_armar_pedido',
            field=models.BooleanField(default=False, help_text='Si desea gestionar el armado de los pedidos, dejar esta casilla en True.'),
        ),
        migrations.AddField(
            model_name='configuracion',
            name='gestionar_entrega',
            field=models.BooleanField(default=False, help_text='Si desea gestionar la entrega de los pedidos de clientes (Fletes, Entregas), dejar esta casilla en True.'),
        ),
    ]
