# Generated by Django 5.0.7 on 2024-10-28 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0017_configuracion_gestionar_armar_pedido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracion',
            name='confirmar_pisar_costo',
            field=models.BooleanField(default=True, help_text='Si desea actualizar el costo unitario de forma automática según la ultima compra, deje esta casilla en True. (En falso, se muestra casilla ✔️ Actualizar Costo en producto comprado)'),
        ),
        migrations.AlterField(
            model_name='configuracion',
            name='editar_fecha_compra',
            field=models.BooleanField(default=False, help_text='Si desea poder editar la fecha en la compra, deje esta casilla en True.'),
        ),
        migrations.AlterField(
            model_name='configuracion',
            name='precio_venta_automatico',
            field=models.BooleanField(default=False, help_text='Si desea que el precio de venta del producto se calcule en base a una rentabilidad sobre el costo, deje esta casilla en True. En el caso contrario, se habilitará una casilla para colocar el precio final de venta.', verbose_name='Precio venta basado en rentabilidad'),
        ),
        migrations.AlterField(
            model_name='configuracion',
            name='valuar_stock_negativo',
            field=models.BooleanField(default=False, help_text='Si desea que el stock negativo reste de su valuacion, deje esta casilla en True.'),
        ),
        migrations.AlterField(
            model_name='configuracion',
            name='venta_stock_negativo',
            field=models.BooleanField(default=False, help_text='Si desea vender sin limites de inventario, deje esta casilla en True. (Genera Stock Negativo)'),
        ),
    ]
