# Generated by Django 5.0.7 on 2024-10-29 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0018_alter_configuracion_confirmar_pisar_costo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracion',
            name='gestionar_armar_pedido',
            field=models.BooleanField(default=True, help_text='Si desea gestionar el armado de los pedidos, dejar esta casilla en True.'),
        ),
        migrations.AlterField(
            model_name='configuracion',
            name='gestionar_entrega',
            field=models.BooleanField(default=True, help_text='Si desea gestionar la entrega de los pedidos de clientes (Fletes, Entregas), dejar esta casilla en True.'),
        ),
        migrations.AlterField(
            model_name='configuracion',
            name='limite_pedidos_pendientes',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='configuracion',
            name='precio_venta_automatico',
            field=models.BooleanField(default=True, help_text='Si desea que el precio de venta del producto se calcule en base a una rentabilidad sobre el costo, deje esta casilla en True. En el caso contrario, se habilitará una casilla para colocar el precio final de venta.', verbose_name='Precio venta basado en rentabilidad'),
        ),
        migrations.AlterField(
            model_name='configuracion',
            name='venta_stock_negativo',
            field=models.BooleanField(default=True, help_text='Si desea vender sin limites de inventario, deje esta casilla en True. (Genera Stock Negativo)'),
        ),
    ]
