# Generated by Django 5.0.7 on 2024-10-29 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0019_alter_configuracion_gestionar_armar_pedido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracion',
            name='unidad_de_medida_precio_venta',
            field=models.BooleanField(default=True, help_text='Permite Modificar la unidad de medida del precio del producto'),
        ),
    ]
