# Generated by Django 5.0.7 on 2024-10-29 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0020_alter_configuracion_unidad_de_medida_precio_venta'),
        ('inventario', '0019_alter_categoria_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracion',
            name='deposito_central',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.deposito'),
        ),
    ]
