# Generated by Django 5.0.7 on 2024-11-01 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0021_configuracion_deposito_central'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracion',
            name='numero_contacto',
            field=models.CharField(default='+541157045506', max_length=15),
        ),
    ]
