# Generated by Django 5.0 on 2024-10-11 16:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agenda', '0013_alter_chofer_usuario'),
        ('inventario', '0008_alter_producto_costo_unitario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=25)),
                ('estado', models.BooleanField(default=False)),
                ('en_transito', models.BooleanField(default=True)),
                ('en_descarga', models.BooleanField(default=True)),
                ('compra_inicial', models.BooleanField(default=False)),
                ('observacion', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('anulada', models.BooleanField(default=False)),
                ('anulada_el', models.DateTimeField(blank=True, null=True)),
                ('anulada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('deposito', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='inventario.deposito', verbose_name='Deposito ingreso')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='agenda.proveedor', verbose_name='Proveedor')),
                ('vendedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='agenda.vendedor', verbose_name='Vendedor')),
            ],
            options={
                'verbose_name': 'compra',
                'verbose_name_plural': '📥 Orden de compra',
            },
        ),
        migrations.CreateModel(
            name='detalleCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('cantidad', models.DecimalField(decimal_places=3, default=1, max_digits=25)),
                ('precio', models.DecimalField(decimal_places=3, default=0, max_digits=25)),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Desc (%)')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=25)),
                ('ActualizarCosto', models.BooleanField(default=True)),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compras.compra')),
                ('deposito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.deposito', verbose_name='Deposito ingreso')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.producto')),
            ],
            options={
                'verbose_name': 'detalle de comrpa',
                'verbose_name_plural': '📦 Productos comprados',
            },
        ),
        migrations.CreateModel(
            name='FleteCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importe', models.DecimalField(decimal_places=2, default=0, max_digits=25)),
                ('camion', models.CharField(blank=True, max_length=255, null=True)),
                ('patente', models.CharField(blank=True, max_length=255, null=True)),
                ('direccion_retiro', models.CharField(blank=True, max_length=255, null=True)),
                ('direccion_descarga', models.CharField(blank=True, max_length=255, null=True)),
                ('ruta_maps', models.URLField(blank=True, max_length=255, null=True)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('cancelado', models.BooleanField(default=False)),
                ('chofer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agenda.chofer')),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compras.compra')),
            ],
            options={
                'verbose_name': 'flete',
                'verbose_name_plural': '🚚 Fletes',
            },
        ),
        migrations.CreateModel(
            name='NotaDeCreditoCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('motivo', models.CharField(max_length=255)),
                ('estado', models.BooleanField(default=False)),
                ('entregado', models.BooleanField(default=False)),
                ('anulada', models.BooleanField(default=False)),
                ('anulada_el', models.DateTimeField(blank=True, null=True)),
                ('anulada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('compra', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='compras.compra', verbose_name='compra')),
            ],
            options={
                'verbose_name': 'Nota de credito',
                'verbose_name_plural': '📕 Notas de credito',
            },
        ),
    ]
