# Generated by Django 5.0 on 2024-10-11 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_alter_compra_en_descarga_alter_compra_en_transito_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallecompra',
            name='detalle',
            field=models.TextField(blank=True, null=True),
        ),
    ]
