# Generated by Django 5.0 on 2024-10-11 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0003_detallecompra_detalle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='vendedor',
        ),
    ]
