# Generated by Django 5.0 on 2024-10-12 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0014_flota'),
        ('compras', '0004_remove_compra_vendedor'),
        ('inventario', '0008_alter_producto_costo_unitario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fletecompra',
            name='camion',
        ),
        migrations.RemoveField(
            model_name='fletecompra',
            name='patente',
        ),
        migrations.AddField(
            model_name='fletecompra',
            name='vehiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agenda.flota'),
        ),
        migrations.AlterField(
            model_name='fletecompra',
            name='direccion_descarga',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.deposito'),
        ),
        migrations.AlterField(
            model_name='fletecompra',
            name='direccion_retiro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agenda.onboardingproveedor'),
        ),
    ]
