# Generated by Django 5.0 on 2024-10-12 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0005_remove_fletecompra_camion_remove_fletecompra_patente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='detalle',
            field=models.TextField(blank=True, help_text='Campo generado automáticamente por el sistema.', null=True),
        ),
        migrations.AlterField(
            model_name='detallecompra',
            name='detalle',
            field=models.TextField(blank=True, help_text='Campo generado automáticamente por el sistema.', null=True),
        ),
    ]
