# Generated by Django 5.0.7 on 2024-10-17 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0007_alter_compra_deposito_alter_compra_proveedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='descargas',
            field=models.IntegerField(default=0),
        ),
    ]
